### ISSUE TITLE
[Story] Update the Connection Class to use waypoints

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/3DuF#428]
### Description

Currently, the `Connection` class is very fragile. We need to update the class to be able to take advantage of the waypoints to auto compute all the connection paths, segments, etc. 

Things to do:

- [ ] Ability to compute segments from wayPoints, paths #425
- [ ] Ability to edit, delete, add new paths #141 
- [ ] Ability to break existing intersections of paths to insert a node #141 #315 
- [ ] Ability to work with curved channels #371

**Additional Description:** 

This will require us to:
1. Change the base data structures we are using for connections and all the dependent computing classes

Acceptance Criteria:
- [ ] Unit Test

**Comment by rkrishnasanka** [comment]
This comment in the pr also is connected to this : https://github.com/CIDARLAB/3DuF/pull/427/files#r742068913
